name: publish
on:
  push:
    branches:
      - master
      - development
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest push
        uses: actions/checkout@v2
      
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          
      - name: Install MkDocs and Dependencies
        run: pip install "mkdocs-material==8.0.3" mkdocs-extra-sass-plugin "mkdocs-minify-plugin>=0.3" "mkdocs-redirects>=1.0" mike
        
      - name: Setup Github
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git checkout master
          
      - name: Deploy old version
        run: | 
          mike delete --all
          mike deploy 1.0 v1
       
      - name: Deploy release version       
        run: |
          git checkout development
          mike deploy 2.0 release
          mike set-default release
          
      - name: Push changes to server
        run: |
          git checkout gh-pages
          git remote set-url --push origin https://actions:$GITHUB_TOKEN@github.com/ExpressLRS/Docs
          git push -f origin gh-pages

      
